name: docibry
description: "docibry: Document Library"

publish_to: "none"

version: 2.1.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6

  bloc: ^8.1.4
  path: ^1.9.0
  permission_handler: ^11.3.1
  dots_indicator: ^3.0.0
  permission_handler_html: ^0.1.3+1

  share_plus: ^10.0.2
  path_provider: ^2.1.4
  image: ^4.2.0
  file_picker: ^8.0.7
  pdf: ^3.11.1
  pdfx: ^2.6.0 # dependable to device_info_plus: ^9.0.0
  device_info_plus: ^10.1.2

  web: ^0.5.1
  html: ^0.15.4
  sembast: ^3.7.3+2
  equatable: ^2.0.5
  universal_html: ^2.2.4
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1

dependency_overrides:
  device_info_plus: ^9.0.0
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
